/*'LVL 1'*/
CREATE TABLE IF NOT EXISTS s_user(
id BIGINT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(250) NOT NULL UNIQUE,
CONSTRAINT s_user_pk PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS s_address(
id BIGINT NOT NULL AUTO_INCREMENT,
store_name VARCHAR(120) NOT NULL,
city VARCHAR(250) NOT NULL,
street_address VARCHAR(250) NOT NULL UNIQUE,
CONSTRAINT s_address_pk PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS s_product(
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(250) NOT NULL UNIQUE,
description VARCHAR(500) NOT NULL,
price DECIMAL(10, 2) NOT NULL,
CONSTRAINT s_product_pk PRIMARY KEY(id)
);


/*'LVL 2'*/
CREATE TABLE IF NOT EXISTS s_order(
id BIGINT NOT NULL AUTO_INCREMENT,
user_id BIGINT NOT NULL,
status VARCHAR(25) NOT NULL,
order_cost DECIMAL(10, 2) NOT NULL,
order_date DATETIME NOT NULL,
address_id BIGINT NOT NULL,
CONSTRAINT s_order_pk PRIMARY KEY(id),

CONSTRAINT order_user_fk FOREIGN KEY(user_id)
    REFERENCES s_user (id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT order_address_fk FOREIGN KEY(address_id)
    REFERENCES s_address (id) ON UPDATE CASCADE ON DELETE RESTRICT
);


/*'LVL 3'*/
CREATE TABLE IF NOT EXISTS s_order_product(
id BIGINT NOT NULL AUTO_INCREMENT,
order_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,
quantity BIGINT NOT NULL,
CONSTRAINT op_pk PRIMARY KEY(id),

CONSTRAINT op_order_fk FOREIGN KEY (order_id)
    REFERENCES s_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT op_product_fk FOREIGN KEY (product_id)
    REFERENCES s_product(id) ON UPDATE CASCADE
);